#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
AnkiFlash Importer
This plugin helps you import flashcards generated by AnkiFlash (https://ankiflash.com/)

Author: Long Ly
Website: https://www.facebook.com/ankiflashcom
Modified: Feb 21, 2021
"""

from aqt import mw
from aqt.qt import *

from .ankiflash_importer import AnkiFlashImporter

version = '0.6.1'
title = 'AnkiFlash Importer ' + version


def importWindow():
    mw.myWidget = window = AnkiFlashImporter(title, version)
    window.keyPressed.connect(window.onKey)
    window.show()


action = QAction(title, mw)
action.triggered.connect(importWindow)
mw.form.menuTools.addAction(action)
