# Form implementation generated from reading ui file '/ankiflash-importer/ui/ui_importer.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiImporter(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(422, 212)
        self.ankiFlashPathTxt = QtWidgets.QLineEdit(parent=Dialog)
        self.ankiFlashPathTxt.setGeometry(QtCore.QRect(120, 13, 281, 31))
        self.ankiFlashPathTxt.setObjectName("ankiFlashPathTxt")
        self.importProgressBar = QtWidgets.QProgressBar(parent=Dialog)
        self.importProgressBar.setGeometry(QtCore.QRect(120, 170, 281, 31))
        font = QtGui.QFont()
        font.setBold(False)
        self.importProgressBar.setFont(font)
        self.importProgressBar.setProperty("value", 0)
        self.importProgressBar.setObjectName("importProgressBar")
        self.checkBox = QtWidgets.QCheckBox(parent=Dialog)
        self.checkBox.setGeometry(QtCore.QRect(18, 137, 381, 17))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.importModeBox = QtWidgets.QComboBox(parent=Dialog)
        self.importModeBox.setGeometry(QtCore.QRect(14, 97, 391, 32))
        self.importModeBox.setObjectName("importModeBox")
        self.importModeBox.addItem("")
        self.importModeBox.addItem("")
        self.importModeBox.addItem("")
        self.deckNameLbl = QtWidgets.QLabel(parent=Dialog)
        self.deckNameLbl.setGeometry(QtCore.QRect(20, 62, 81, 16))
        font = QtGui.QFont()
        font.setBold(False)
        self.deckNameLbl.setFont(font)
        self.deckNameLbl.setObjectName("deckNameLbl")
        self.deckNameTxt = QtWidgets.QLineEdit(parent=Dialog)
        self.deckNameTxt.setGeometry(QtCore.QRect(120, 56, 281, 31))
        self.deckNameTxt.setObjectName("deckNameTxt")
        self.ankiFlashPathBtn = QtWidgets.QPushButton(parent=Dialog)
        self.ankiFlashPathBtn.setGeometry(QtCore.QRect(11, 15, 100, 32))
        self.ankiFlashPathBtn.setStyleSheet(
            "background-color: grey; border-radius: 5px; margin-top: 5px; margin-bottom: 5px;"
        )
        self.ankiFlashPathBtn.setObjectName("ankiFlashPathBtn")
        self.importBtn = QtWidgets.QPushButton(parent=Dialog)
        self.importBtn.setGeometry(QtCore.QRect(10, 170, 100, 32))
        self.importBtn.setObjectName("importBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AnkiFlash Importer"))
        self.ankiFlashPathTxt.setPlaceholderText(
            _translate("Dialog", " Select AnkiFlash Folder Path")
        )
        self.checkBox.setText(
            _translate("Dialog", "Overwite if the note type already exists?")
        )
        self.importModeBox.setItemText(
            0,
            _translate(
                "Dialog", "1. Import even if existing note has same first field"
            ),
        )
        self.importModeBox.setItemText(
            1, _translate("Dialog", "2. Update existing notes when first field matches")
        )
        self.importModeBox.setItemText(
            2, _translate("Dialog", "3. Ignore if first field match existing note")
        )
        self.deckNameLbl.setText(_translate("Dialog", "Deck Name"))
        self.deckNameTxt.setPlaceholderText(_translate("Dialog", " Input Deck Name"))
        self.ankiFlashPathBtn.setText(_translate("Dialog", "AnkiFlash Path"))
        self.importBtn.setText(_translate("Dialog", "Import"))
