# Form implementation generated from reading ui file '/ankiflash-importer/ui/ui_change_map.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiChangeMap(object):
    def setupUi(self, ChangeMap):
        ChangeMap.setObjectName("ChangeMap")
        ChangeMap.resize(391, 335)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("../resources/anki.ico"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        ChangeMap.setWindowIcon(icon)
        ChangeMap.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        ChangeMap.setAutoFillBackground(False)
        self.fields = QtWidgets.QListWidget(parent=ChangeMap)
        self.fields.setGeometry(QtCore.QRect(10, 35, 371, 261))
        self.fields.setObjectName("fields")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ChangeMap)
        self.buttonBox.setGeometry(QtCore.QRect(310, 300, 69, 32))
        self.buttonBox.setStyleSheet(
            "background-color: #1DA8AF; color: white; border-radius: 5px; width: 70px; height: 20px;"
        )
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(parent=ChangeMap)
        self.label.setGeometry(QtCore.QRect(12, 10, 97, 16))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(ChangeMap)
        self.buttonBox.accepted.connect(ChangeMap.accept)  # type: ignore
        self.buttonBox.rejected.connect(ChangeMap.reject)  # type: ignore
        self.fields.doubleClicked["QModelIndex"].connect(ChangeMap.accept)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ChangeMap)

    def retranslateUi(self, ChangeMap):
        _translate = QtCore.QCoreApplication.translate
        ChangeMap.setWindowTitle(_translate("ChangeMap", "Map to AnkiFlash Fields"))
        self.label.setText(_translate("ChangeMap", "AnkiFlash Fields"))
