# Form implementation generated from reading ui file '/ankiflash-importer/ui/ui_fields_updater.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiFieldsUpdater(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(570, 352)
        self.importProgressBar = QtWidgets.QProgressBar(parent=Dialog)
        self.importProgressBar.setGeometry(QtCore.QRect(130, 310, 421, 31))
        font = QtGui.QFont()
        font.setBold(False)
        self.importProgressBar.setFont(font)
        self.importProgressBar.setProperty("value", 0)
        self.importProgressBar.setObjectName("importProgressBar")
        self.mappingGroup = QtWidgets.QGroupBox(parent=Dialog)
        self.mappingGroup.setGeometry(QtCore.QRect(20, 50, 531, 251))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mappingGroup.sizePolicy().hasHeightForWidth())
        self.mappingGroup.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.mappingGroup.setFont(font)
        self.mappingGroup.setObjectName("mappingGroup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mappingGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.mappingArea = QtWidgets.QScrollArea(parent=self.mappingGroup)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mappingArea.sizePolicy().hasHeightForWidth())
        self.mappingArea.setSizePolicy(sizePolicy)
        self.mappingArea.setMinimumSize(QtCore.QSize(400, 150))
        self.mappingArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.mappingArea.setWidgetResizable(True)
        self.mappingArea.setObjectName("mappingArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 499, 197))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.mappingArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.mappingArea, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.ankiFlashPathTxt = QtWidgets.QLineEdit(parent=Dialog)
        self.ankiFlashPathTxt.setGeometry(QtCore.QRect(130, 10, 421, 31))
        self.ankiFlashPathTxt.setObjectName("ankiFlashPathTxt")
        self.ankiFlashPathBtn = QtWidgets.QPushButton(parent=Dialog)
        self.ankiFlashPathBtn.setGeometry(QtCore.QRect(20, 10, 100, 32))
        self.ankiFlashPathBtn.setStyleSheet(
            "background-color: grey; border-radius: 5px; margin-top: 5px; margin-bottom: 5px;"
        )
        self.ankiFlashPathBtn.setObjectName("ankiFlashPathBtn")
        self.updateBtn = QtWidgets.QPushButton(parent=Dialog)
        self.updateBtn.setGeometry(QtCore.QRect(20, 310, 100, 32))
        self.updateBtn.setObjectName("updateBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AnkiFlash Fields Updater"))
        self.mappingGroup.setTitle(
            _translate(
                "Dialog", "Field Mapping [Your fields mapped to AnkiFlash's fields]"
            )
        )
        self.ankiFlashPathTxt.setPlaceholderText(
            _translate("Dialog", " Select AnkiFlash Folder Path")
        )
        self.ankiFlashPathBtn.setText(_translate("Dialog", "AnkiFlash Path"))
        self.updateBtn.setText(_translate("Dialog", "Update"))
