# Form implementation generated from reading ui file '/ankiflash-importer/ui/ui_generator.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiGenerator(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(511, 589)
        Dialog.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("../resources/anki.ico"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        Dialog.setWindowIcon(icon)
        Dialog.setAutoFillBackground(True)
        self.inputBox = QtWidgets.QGroupBox(parent=Dialog)
        self.inputBox.setGeometry(QtCore.QRect(10, 10, 491, 411))
        font = QtGui.QFont()
        font.setBold(True)
        self.inputBox.setFont(font)
        self.inputBox.setObjectName("inputBox")
        self.inputTxt = QtWidgets.QPlainTextEdit(parent=self.inputBox)
        self.inputTxt.setGeometry(QtCore.QRect(20, 40, 451, 231))
        font = QtGui.QFont()
        font.setBold(False)
        self.inputTxt.setFont(font)
        self.inputTxt.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.inputTxt.setLineWrapMode(QtWidgets.QPlainTextEdit.LineWrapMode.NoWrap)
        self.inputTxt.setObjectName("inputTxt")
        self.totalLbl = QtWidgets.QLabel(parent=self.inputBox)
        self.totalLbl.setGeometry(QtCore.QRect(20, 277, 191, 16))
        font = QtGui.QFont()
        font.setBold(False)
        self.totalLbl.setFont(font)
        self.totalLbl.setObjectName("totalLbl")
        self.keywordCx = QtWidgets.QComboBox(parent=self.inputBox)
        self.keywordCx.setGeometry(QtCore.QRect(245, 324, 161, 26))
        self.keywordCx.setStyleSheet("")
        self.keywordCx.setObjectName("keywordCx")
        self.keywordLbl = QtWidgets.QLabel(parent=self.inputBox)
        self.keywordLbl.setGeometry(QtCore.QRect(254, 303, 61, 20))
        font = QtGui.QFont()
        font.setBold(False)
        self.keywordLbl.setFont(font)
        self.keywordLbl.setObjectName("keywordLbl")
        self.mappingBtn = QtWidgets.QPushButton(parent=self.inputBox)
        self.mappingBtn.setGeometry(QtCore.QRect(250, 370, 113, 32))
        font = QtGui.QFont()
        font.setBold(False)
        self.mappingBtn.setFont(font)
        self.mappingBtn.setStyleSheet(
            "background-color: grey; border-radius: 5px; margin-top: 5px; margin-bottom: 5px;"
        )
        self.mappingBtn.setObjectName("mappingBtn")
        self.importBtn = QtWidgets.QPushButton(parent=self.inputBox)
        self.importBtn.setGeometry(QtCore.QRect(10, 370, 113, 32))
        font = QtGui.QFont()
        font.setBold(False)
        self.importBtn.setFont(font)
        self.importBtn.setStyleSheet(
            "background-color: grey; border-radius: 5px; margin-top: 5px; margin-bottom: 5px;"
        )
        self.importBtn.setObjectName("importBtn")
        self.copyBtn = QtWidgets.QPushButton(parent=self.inputBox)
        self.copyBtn.setGeometry(QtCore.QRect(10, 320, 111, 32))
        font = QtGui.QFont()
        font.setBold(False)
        self.copyBtn.setFont(font)
        self.copyBtn.setStyleSheet(
            "background-color: grey; border-radius: 5px; margin-top: 5px; margin-bottom: 5px;"
        )
        self.copyBtn.setObjectName("copyBtn")
        self.ankiflashInfoBox = QtWidgets.QGroupBox(parent=Dialog)
        self.ankiflashInfoBox.setGeometry(QtCore.QRect(10, 436, 491, 141))
        font = QtGui.QFont()
        font.setBold(True)
        self.ankiflashInfoBox.setFont(font)
        self.ankiflashInfoBox.setObjectName("ankiflashInfoBox")
        self.buycoffee = QtWidgets.QLabel(parent=self.ankiflashInfoBox)
        self.buycoffee.setGeometry(QtCore.QRect(20, 107, 811, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setItalic(False)
        self.buycoffee.setFont(font)
        self.buycoffee.setOpenExternalLinks(True)
        self.buycoffee.setObjectName("buycoffee")
        self.inbox = QtWidgets.QLabel(parent=self.ankiflashInfoBox)
        self.inbox.setGeometry(QtCore.QRect(20, 83, 391, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setItalic(False)
        self.inbox.setFont(font)
        self.inbox.setObjectName("inbox")
        self.caption = QtWidgets.QLabel(parent=self.ankiflashInfoBox)
        self.caption.setGeometry(QtCore.QRect(20, 30, 391, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setBold(False)
        font.setItalic(True)
        self.caption.setFont(font)
        self.caption.setObjectName("caption")
        self.support = QtWidgets.QLabel(parent=self.ankiflashInfoBox)
        self.support.setGeometry(QtCore.QRect(20, 57, 391, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(False)
        font.setItalic(False)
        self.support.setFont(font)
        self.support.setOpenExternalLinks(True)
        self.support.setTextInteractionFlags(
            QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse
        )
        self.support.setObjectName("support")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AnkiFlash"))
        self.inputBox.setTitle(_translate("Dialog", "Input"))
        self.inputTxt.setPlaceholderText(_translate("Dialog", "Input your words"))
        self.totalLbl.setText(_translate("Dialog", "Total: 0"))
        self.keywordLbl.setText(_translate("Dialog", "Keyword"))
        self.mappingBtn.setToolTip(
            _translate("Dialog", "To update existing flashcards with mapping fields")
        )
        self.mappingBtn.setText(_translate("Dialog", "Mapping"))
        self.importBtn.setToolTip(
            _translate("Dialog", "Cick here to import / create new cards.")
        )
        self.importBtn.setText(_translate("Dialog", "Import"))
        self.copyBtn.setToolTip(
            _translate(
                "Dialog",
                "Copy input words then paste into AnkiFlash Generator Chrome Extension to generate flashcards.",
            )
        )
        self.copyBtn.setText(_translate("Dialog", "Copy Inputs"))
        self.ankiflashInfoBox.setTitle(_translate("Dialog", "AnkiFlash Info"))
        self.buycoffee.setText(
            _translate(
                "Dialog",
                '<html><head/><body><p>If you want to buy me a coffee: <a href="https://www.buymeacoffee.com/longhoangly">https://www.buymeacoffee.com/longhoangly</a></p></body></html>',
            )
        )
        self.inbox.setText(
            _translate(
                "Dialog", "Feel free to drop me a message if any issue or suggestion"
            )
        )
        self.caption.setText(
            _translate("Dialog", "Always beside and help you to learn vocabularies")
        )
        self.support.setText(
            _translate(
                "Dialog",
                'Support: <a href="https://www.facebook.com/ankiflashcom/inbox" target="_blank">https://www.facebook.com/ankiflashcom/inbox</a>',
            )
        )
