# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/ankiflash-importer/ui/ui_change_map.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiChangeMap(object):
    def setupUi(self, ChangeMap):
        ChangeMap.setObjectName("ChangeMap")
        ChangeMap.resize(391, 360)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/anki.ico"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ChangeMap.setWindowIcon(icon)
        self.vboxlayout = QtWidgets.QVBoxLayout(ChangeMap)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtWidgets.QLabel(ChangeMap)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.fields = QtWidgets.QListWidget(ChangeMap)
        self.fields.setObjectName("fields")
        self.vboxlayout.addWidget(self.fields)
        self.buttonBox = QtWidgets.QDialogButtonBox(ChangeMap)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(ChangeMap)
        self.buttonBox.accepted.connect(ChangeMap.accept)  # type: ignore
        self.buttonBox.rejected.connect(ChangeMap.reject)  # type: ignore
        self.fields.doubleClicked['QModelIndex'].connect(
            ChangeMap.accept)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ChangeMap)

    def retranslateUi(self, ChangeMap):
        _translate = QtCore.QCoreApplication.translate
        ChangeMap.setWindowTitle(_translate(
            "ChangeMap", "Map to AnkiFlash Fields"))
        self.label.setText(_translate("ChangeMap", "AnkiFlash Fields"))
