# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/ankiflash-importer/ui/ui_importer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiImporter(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(422, 181)
        self.deckNameTxt = QtWidgets.QLineEdit(Dialog)
        self.deckNameTxt.setGeometry(QtCore.QRect(100, 10, 301, 31))
        self.deckNameTxt.setObjectName("deckNameTxt")
        self.importProgressBar = QtWidgets.QProgressBar(Dialog)
        self.importProgressBar.setGeometry(QtCore.QRect(100, 133, 301, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.importProgressBar.setFont(font)
        self.importProgressBar.setProperty("value", 0)
        self.importProgressBar.setObjectName("importProgressBar")
        self.deckNameLbl = QtWidgets.QLabel(Dialog)
        self.deckNameLbl.setGeometry(QtCore.QRect(20, 18, 81, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.deckNameLbl.setFont(font)
        self.deckNameLbl.setObjectName("deckNameLbl")
        self.importBtn = QtWidgets.QPushButton(Dialog)
        self.importBtn.setEnabled(False)
        self.importBtn.setGeometry(QtCore.QRect(20, 133, 75, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.importBtn.setFont(font)
        self.importBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.importBtn.setAutoFillBackground(False)
        self.importBtn.setCheckable(False)
        self.importBtn.setDefault(False)
        self.importBtn.setObjectName("importBtn")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(21, 103, 381, 17))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.importModeBox = QtWidgets.QComboBox(Dialog)
        self.importModeBox.setGeometry(QtCore.QRect(16, 60, 391, 32))
        self.importModeBox.setObjectName("importModeBox")
        self.importModeBox.addItem("")
        self.importModeBox.addItem("")
        self.importModeBox.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "AnkiFlash Importer"))
        self.deckNameTxt.setPlaceholderText(
            _translate("Dialog", " Input deck name"))
        self.deckNameLbl.setText(_translate("Dialog", "Deck Name"))
        self.importBtn.setToolTip(_translate(
            "Dialog", "Import generated flashcards into Anki"))
        self.importBtn.setText(_translate("Dialog", "Import"))
        self.checkBox.setText(_translate(
            "Dialog", "Overwite if the note type already exists?"))
        self.importModeBox.setItemText(0, _translate(
            "Dialog", "1. Import even if existing note has same first field"))
        self.importModeBox.setItemText(1, _translate(
            "Dialog", "2. Update existing notes when first field matches"))
        self.importModeBox.setItemText(2, _translate(
            "Dialog", "3. Ignore if first field match existing note"))
